name: Deploy Backend on AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecmm_backend .
      - name: Publish image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/ecmm_backend:latest

    deploy: 
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull image from docker hub
          run: docker pull ${{secrets.DOCKER_USERNAME}}/ecmm_backend:latest
        - name: Delete old container
          run: docker rm -f ecmm_backend_container
        - name: Run Docker container  
          run: docker run -d -p 4000:4000 -name ecmm_backend_container -e MONGO_URI=${{ secrets.MONGO_URI }} ${{ secrets.DOCKER_USERNAME }}/ecmm_backend:latest